CloudVLab/terraform-lab-foundation

gce_instance/README.md

GCE migration

---

gce_instance/README.md

Migrate to Terraform Modules
Add standard formatting for modules
Ref: [Terraform Modules with Qwiklabs](https://docs.google.com/document/d/1hOjwB3IgMbqs8EO0ywzTkomdN8UzchfNXzUt0UC7dn4/edit?resourcekey=0-spwoDWgdn1G5f1YLeKEcpw#heading=h.5x0d5h95i329)

GCE Documentation

---

README.md
gke_cluster/README.md
gke_cluster/cloudbuild.yaml
gke_cluster/stable/main.tf
gke_cluster/stable/outputs.tf
gke_cluster/stable/provider.tf
gke_cluster/stable/runtime.yaml
gke_cluster/stable/variables.tf
gke_cluster/stable/vpc.tf

Migrate to Terraform Modules
| Module | Description | 
|------|----------|
| GKE Cluster | Create a GKE Cluster |
Ref: [Terraform Modules with Qwiklabs](https://docs.google.com/document/d/1hOjwB3IgMbqs8EO0ywzTkomdN8UzchfNXzUt0UC7dn4/edit?resourcekey=0-spwoDWgdn1G5f1YLeKEcpw#heading=h.5x0d5h95i329)

Gke module

---

README.md
basics/gcs_bucket/README.md
basics/gcs_bucket/cloudbuild.yaml
basics/gcs_bucket/stable/main.tf
basics/gcs_bucket/stable/outputs.tf
basics/gcs_bucket/stable/provider.tf
basics/gcs_bucket/stable/runtime.yaml
basics/gcs_bucket/stable/variables.tf

Migrate to Terraform Modules
* Added GCS example
* Update solution + basics documentation
Ref: [Terraform Modules with Qwiklabs](https://docs.google.com/document/d/1hOjwB3IgMbqs8EO0ywzTkomdN8UzchfNXzUt0UC7dn4/edit?resourcekey=0-spwoDWgdn1G5f1YLeKEcpw#heading=h.5x0d5h95i329)

Basics gcs

---

README.md
basics/vpc_network/README.md
basics/vpc_network/cloudbuild.yaml
basics/vpc_network/stable/main.tf
basics/vpc_network/stable/outputs.tf
basics/vpc_network/stable/provider.tf
basics/vpc_network/stable/runtime.yaml
basics/vpc_network/stable/variables.tf

VPC
* Add networks
* Add subnetwork
__NOTE:__ Custom networks require firewall rules. The default custom network will not provide access via the usual protocols.
Ref: [Terraform Modules with Qwiklabs](https://docs.google.com/document/d/1hOjwB3IgMbqs8EO0ywzTkomdN8UzchfNXzUt0UC7dn4/edit?resourcekey=0-spwoDWgdn1G5f1YLeKEcpw#heading=h.5x0d5h95i329)

Add: Virtual Private Network module

---

CHANNELS.md
README.md
basics/gce_instance/stable/test.tfvars
basics/gke_cluster/cloudbuild.yaml
basics/gke_cluster/stable/test.tfvars
basics/gke_cluster/stable/variables.tf

Update docs + ref for SA and API access.

Fix resources

---

basics/gcs_bucket/README.md
basics/gcs_bucket/stable/main.tf
basics/gcs_bucket/stable/outputs.tf
basics/gcs_bucket/stable/variables.tf

Vertex export/import requires storageclass access.

Terraform Lab Foundation: Fix Storage Class

---

basics/gce_instance/README.md
basics/gce_instance/stable/main.tf
basics/gce_instance/stable/variables.tf

Add startup-script to gce_instance.

Add: Enable startup scripts

---

solutions/bigquery_soccer/stable/main.tf

Amend BigQuery to use the project region + location.

Add: Location  + Project properties

---

solutions/bigquery_soccer/stable/main.tf

Reverts CloudVLab/terraform-lab-foundation#20
Requires additional value

Revert "Add: Location  + Project properties"

---

solutions/bigquery_soccer/stable/main.tf

Add: Location  + Project properties definition

---

solutions/bigquery_soccer/stable/main.tf

Add: Job project ref

---

solutions/bigquery_soccer/stable/main.tf
solutions/bigquery_soccer/stable/variables.tf

Add: Isolated region/location for BQ

https://buganizer.corp.google.com/issues/209449870

---

basics/gce_instance/README.md
basics/gce_instance/example/lab-init
basics/gce_instance/example/main.tf
basics/gce_instance/example/outputs.tf
basics/gce_instance/example/runtime.yaml
basics/gce_instance/example/variables.tf

GCE example configuration

---

basics/gce_instance/README.md
basics/gce_instance/example/README.md

Update example reference configuration for GCE Instance

GCE reference

---

basics/vai_notebook/stable/main.tf

Add: instance owner change to service account

---

solutions/ide_web/stable/main.tf

Add: Migrate to new firewall module

---

solutions/ide_web/stable/main.tf
solutions/ide_web/stable/variables.tf

Remove module dependencies - so can call sub modules.

Add: Module dependencies

---

solutions/ide_web/stable/main.tf
solutions/ide_web/stable/variables.tf

Add: Amend variable names for modules

---

basics/vpc_connector/README.md
basics/vpc_connector/stable/main.tf
basics/vpc_connector/stable/outputs.tf
basics/vpc_connector/stable/variables.tf

Amend variables + add new output variable.

Add: Rename variable + new output variable

---

basics/vpc_connector/stable/provider.tf

Add: include Google Beta provider

---

basics/gcs_bucket/example/README.md
basics/gcs_bucket/example/main.tf
basics/gcs_bucket/example/outputs.tf
basics/gcs_bucket/example/runtime.yaml
basics/gcs_bucket/example/variables.tf
basics/vai_notebook/example/main.tf
basics/vpc_connector/example/scripts/lab-init
basics/vpc_firewall/README.md
basics/vpc_firewall/example/scripts/lab-init

Add: example updates

---

solutions/ide_web/stable/main.tf

Add: Phase 2 - replace Serverless VPC access + GCE ref

---

solutions/ide_web/stable/main.tf

Add: network change to subnet

---

README.md
solutions/README.md

Update AppSheet + CloudSQL reference documentation

Add: Ref to AppSheet + CloudSQL

---

README.md
basics/cloudsql/README.md
basics/cloudsql/cloudbuild.yaml
basics/cloudsql/example/main.tf
basics/cloudsql/example/outputs.tf
basics/cloudsql/example/runtime.yaml
basics/cloudsql/example/variables.tf
basics/cloudsql/stable/main.tf
basics/cloudsql/stable/output.tf
basics/cloudsql/stable/provider.tf
basics/cloudsql/stable/runtime.yaml
basics/cloudsql/stable/variable.tf

Add: cloudsql reference

---

basics/vpc_network/stable/outputs.tf

Enable additional output variable for Linking networks.

Add: VPC self_link output variable

---

basics/vpc_network/README.md
basics/vpc_network/stable/outputs.tf

Add network self_link to the output variables

Add: network self link

---

solutions/README.md
solutions/ide_tensorflow/README.md
solutions/ide_tensorflow/cloudbuild.yaml
solutions/ide_tensorflow/example/README.md
solutions/ide_tensorflow/example/main.tf
solutions/ide_tensorflow/example/outputs.tf
solutions/ide_tensorflow/example/runtime.yaml
solutions/ide_tensorflow/example/scripts/lab-init
solutions/ide_tensorflow/example/variables.tf
solutions/ide_tensorflow/stable/main.tf
solutions/ide_tensorflow/stable/outputs.tf
solutions/ide_tensorflow/stable/provider.tf
solutions/ide_tensorflow/stable/runtime.yaml
solutions/ide_tensorflow/stable/variables.tf

Tlf maintenance

---

basics/api_service/README.md
basics/api_service/example/README.md
basics/api_service/example/main.tf
basics/api_service/example/runtime.yaml
basics/api_service/example/variables.tf

Add: API service example

---

basics/api_service/example/variables.tf

Add: variable comments

---

solutions/ide_cloud_code/example/main.tf

Amend Example code:
- [x[ GKE cluster is private by default

Add: amend the example to point to the github repo

---

solutions/ide_cloud_code/stable/main.tf

Reference: [terraform-provider-google](https://github.com/hashicorp/terraform-provider-google/issues/10782)

Add: https://github.com/hashicorp/terraform-provider-google/issues/10782

---

solutions/ide_cloud_code/stable/main.tf

Reverts CloudVLab/terraform-lab-foundation#59

Revert "Add: https://github.com/hashicorp/terraform-provider-google/issues/10782"

---

solutions/ide_cloud_code/example/README.md
solutions/ide_cloud_code/example/install.sh

Added easy installation script.

Example TF code installation script

---

solutions/ide_tensorflow/example/README.md
solutions/ide_tensorflow/example/install.sh
solutions/ide_web/example/README.md
solutions/ide_web/example/install.sh

Add: install.sh

---

solutions/CHANGELOG.md
solutions/ide_cloud_code/dev/main.tf
solutions/ide_cloud_code/dev/outputs.tf
solutions/ide_cloud_code/dev/provider.tf
solutions/ide_cloud_code/dev/runtime.yaml
solutions/ide_cloud_code/dev/variables.tf

Module: solutions/ide_cloud_code
Introduce new channel for development. 
Add general changelog for breaking changes + enhancements.

Add: Rename of conditional variables

---

solutions/ide_cloud_code/dev/main.tf

Remove reference to old variable names.

Add: updated variable names

---

solutions/ide_cloud_code/dev/main.tf
solutions/ide_cloud_code/dev/variables.tf

Experimentation with GKE settings

Add: gke bin auth config

---

solutions/ide_cloud_code/dev/main.tf
solutions/ide_cloud_code/dev/variables.tf

Fix: Invalid section for bin auth applied to the config.

Add: bin auth rename and move to correct section

---

solutions/ide_cloud_code/dev/main.tf

Add addons_config section to manage the enable setting for the GKE cluster.

Add: addons_config section for settings

---

solutions/ide_cloud_code/dev/main.tf
solutions/ide_cloud_code/dev/variables.tf

Update: GKE configuration
- Add template for Addons + ip_allocation_policy

Add: GKE config updates

---

basics/gke_cluster/dev/main.tf
basics/gke_cluster/dev/outputs.tf
basics/gke_cluster/dev/provider.tf
basics/gke_cluster/dev/runtime.yaml
basics/gke_cluster/dev/test.tfvars
basics/gke_cluster/dev/variables.tf
basics/gke_cluster/dev/vpc.tf
solutions/ide_cloud_code/dev/main.tf

Amend 
Going forward, both should now use the same configuration
Todo:

Tlf solutions

---

solutions/ide_gke_developer/README.md
solutions/ide_gke_developer/cloudbuild.yaml
solutions/ide_gke_developer/dev/main.tf
solutions/ide_gke_developer/dev/outputs.tf
solutions/ide_gke_developer/dev/provider.tf
solutions/ide_gke_developer/dev/runtime.yaml
solutions/ide_gke_developer/dev/variables.tf
solutions/ide_gke_developer/example/README.md
solutions/ide_gke_developer/example/install.sh
solutions/ide_gke_developer/example/main.tf
solutions/ide_gke_developer/example/outputs.tf
solutions/ide_gke_developer/example/runtime.yaml
solutions/ide_gke_developer/example/variables.tf

Moved code to its own solution.
Will refactor later - just want to get the general configuration working.

Test: Developer day code

---

solutions/ide_gke_developer/dev/main.tf

Add: conditional validation

---

solutions/ide_gke_developer/dev/main.tf

Add: fix for validation

---

solutions/ide_gke_developer/dev/main.tf

Temp fix - conflict between autopilot flag and bin authz

Add: Fix logic

---

solutions/ide_gke_developer/dev/main.tf

Replace false settings with null.

Add: replace false status with null setting

---

solutions/ide_gke_developer/dev/main.tf

Remove Invalid section for gke autopilot + bin authz.

Fix: move invalid config

---

README.md
solutions/README.md
solutions/proxy_vertex_workbench/README.md
solutions/proxy_vertex_workbench/dev/main.tf
solutions/proxy_vertex_workbench/dev/outputs.tf
solutions/proxy_vertex_workbench/dev/provider.tf
solutions/proxy_vertex_workbench/dev/runtime.yaml
solutions/proxy_vertex_workbench/dev/variables.tf
solutions/proxy_vertex_workbench/example/README.md
solutions/proxy_vertex_workbench/example/install.sh
solutions/proxy_vertex_workbench/example/main.tf
solutions/proxy_vertex_workbench/example/outputs.tf
solutions/proxy_vertex_workbench/example/runtime.yaml
solutions/proxy_vertex_workbench/example/variables.tf

Vertex proxy

---

solutions/proxy_vertex_workbench/dev/outputs.tf
solutions/proxy_vertex_workbench/example/outputs.tf

Amend output variable name to be consistent.

Add: change to output variables

---

solutions/proxy_vertex_workbench/dev/main.tf

Rename the image family value.
| old | new |
|-----|-------|
| gceImageFamily | gceInstanceImage |

Add: rename image name

---

solutions/proxy_vertex_workbench/README.md

Ensure the general documentation matches the implementation.

Add: endpoint reassignment

---

basics/gke_cluster/dev/main.tf

Update configuration to add Enable IP

Add: Enable IP properties

---

basics/gke_cluster/dev/main.tf

Amend the default to null. 
The intention is to amend the network/subnetwork to default.

Add: default network to null

---

basics/gke_cluster/dev/vpc.tf

Add: comment out vpc.tf

---

solutions/ide_cloud_code/example/README.md

Amend the template for example documentation.

Add: docs for install.sh

---

solutions/ide_cloud_code/dev/main.tf

Add: gke definition

---

solutions/ide_cloud_code/dev/variables.tf

Add missing variables for not using custom network.

Add: gkeNetwork + gkeSubnetwork

---

basics/gce_instance/example/README.md
basics/gce_instance/example/install.sh

Add: Docs for gce install

---

basics/gce_instance/example/install.sh

Fix error on sub-directory creation.

Add: quotation on directory path!

---

basics/gce_instance/example/variables.tf

Remove old variable definitions.

Remove: old variable definitions

---

basics/gce_instance/stable/main.tf

Add temporary change to hide service account.

Add: temp fix

---

solutions/ide_cloud_code/dev/main.tf
solutions/ide_cloud_code/dev/variables.tf

Add: null definition for false value

---

solutions/ide_cloud_code/dev/main.tf

Add master_authorized_networks_config

Add: master authorized network config

---

solutions/ide_cloud_code/dev/main.tf

Add: block code correction

---

solutions/ide_cloud_code/dev/main.tf

Add IP Alias for GKE ref: [Terraform GKE](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster)

Add: IP Alias config

---

solutions/ide_cloud_code/dev/main.tf

Add: comment out authorized master block

---

solutions/ide_cloud_code/dev/main.tf

Amend the private cluster value when false.

Add: private cluster false value

---

solutions/ide_cloud_code/dev/main.tf

Patch - private node setting to provide true/false value.

Add: Private endpoint value is mandatory

---

solutions/ide_web/dev/variables.tf

Remove the optional status of username

Add: default username

---

solutions/ide_gke_developer/dev/main.tf
solutions/ide_gke_developer/dev/variables.tf

Add: isolate GKE definition

---

solutions/lab_proxy/dev/main.tf
solutions/lab_proxy/dev/variables.tf

Add missing variable definitions.

Add: Proxy variable update

---

solutions/lab_proxy/dev/main.tf
solutions/lab_proxy/dev/variables.tf

Add: custom proxy image

---

basics/gce_instance/stable/main.tf
basics/gce_instance/stable/variables.tf

Add: Can IP forward property to GCE

---

solutions/proxy_vertex_workbench/example/README.md

Vertex Notebook - Proxy Module

Fix: user docs + bash install

---

solutions/proxy_vertex_workbench/example/install.sh

Defect: using the wrong raw url for the file download.

Fix: bash install reference

---

basics/vai_notebook/example/README.md

Update doc to include location of startup script.

Add: startup script location

---

basics/secret_manager/stable/main.tf

Add: name change to secret id + data

---

solutions/ide_cloud_code/example/README.md

Add: example custom output

---

solutions/ide_cloudshell/README.md
solutions/ide_cloudshell/cloudbuild.yaml
solutions/ide_cloudshell/example/README.md
solutions/ide_cloudshell/example/install.sh
solutions/ide_cloudshell/example/main.tf
solutions/ide_cloudshell/example/outputs.tf
solutions/ide_cloudshell/example/runtime.yaml
solutions/ide_cloudshell/example/scripts/lab-init
solutions/ide_cloudshell/example/variables.tf
solutions/ide_cloudshell/stable/main.tf
solutions/ide_cloudshell/stable/outputs.tf
solutions/ide_cloudshell/stable/provider.tf
solutions/ide_cloudshell/stable/runtime.yaml
solutions/ide_cloudshell/stable/variables.tf

New IDE for Cloudshell alternative

Add: Cloudshell alternative

---

solutions/proxy_vertex_workbench/dev/main.tf

Fix: Provider requires project property

---

solutions/proxy_vertex_workbench/dev/main.tf

Update VPC connector to create a random identifier.

Add: unique id for vpc connector

---

solutions/proxy_vertex_workbench/dev/main.tf

Add project missing from Vertex Notebook

Add: project to Vertex AI Notebook

---

solutions/proxy_vertex_workbench/README.md
solutions/proxy_vertex_workbench/example/main.tf
solutions/proxy_vertex_workbench/stable/main.tf
solutions/proxy_vertex_workbench/stable/outputs.tf
solutions/proxy_vertex_workbench/stable/runtime.yaml
solutions/proxy_vertex_workbench/stable/variables.tf

Enable stable version.
Promote the dev version of the Proxy Workbench.

Add: Stable version of Proxy Vertex Workbench

---

basics/api_service/example/README.md
basics/api_service/example/install.sh

Add the missing installation script

API_SERVICE: Add installation script

---

basics/cloud_run/README.md
basics/cloud_run/cloudbuild.yaml
basics/cloud_run/example/README.md
basics/cloud_run/example/install.sh
basics/cloud_run/example/main.tf
basics/cloud_run/example/outputs.tf
basics/cloud_run/example/runtime.yaml
basics/cloud_run/example/scripts/lab-init
basics/cloud_run/example/variables.tf
basics/cloud_run/stable/main.tf
basics/cloud_run/stable/outputs.tf
basics/cloud_run/stable/runtime.yaml
basics/cloud_run/stable/test.tfvars
basics/cloud_run/stable/variables.tf
basics/secret_manager/stable/main.tf
basics/secret_manager/stable/outputs.tf

Create new Cloud Run module for AutoML Proxy

New Cloud Run Module

---

basics/cloud_run/README.md
basics/cloud_run/stable/variables.tf

Amend docs to reflect the Cloud Run use case.

Add: doc update for cloud run

---

basics/cloud_run/README.md

Remove notes for use of Cloud Run.

Add: docs update

---

solutions/proxy_automl/example/main.tf

Replace the use of an incorrect channel.

Add: replace incorrect channel

---

solutions/ide_cloudshell/dev/main.tf
solutions/ide_cloudshell/dev/outputs.tf
solutions/ide_cloudshell/dev/provider.tf
solutions/ide_cloudshell/dev/runtime.yaml
solutions/ide_cloudshell/dev/variables.tf

Add Dev Channel change based on restriction on external IPs.
Amend solution to:

Add: Migrate to IAP and use internal IP

---

solutions/ide_cloudshell/dev/main.tf

Default to platform region/zone values.

Add: default to platform region/zone

---

solutions/ide_cloudshell/dev/main.tf
solutions/ide_cloudshell/dev/variables.tf

Add: Google Private Access - IAP internal access

---

solutions/cloud_labshell/README.md
solutions/cloud_labshell/cloudbuild.yaml
solutions/cloud_labshell/example/README.md
solutions/cloud_labshell/example/install.sh
solutions/cloud_labshell/example/main.tf
solutions/cloud_labshell/example/outputs.tf
solutions/cloud_labshell/example/runtime.yaml
solutions/cloud_labshell/example/scripts/lab-init
solutions/cloud_labshell/example/variables.tf
solutions/cloud_labshell/stable/main.tf
solutions/cloud_labshell/stable/outputs.tf
solutions/cloud_labshell/stable/provider.tf
solutions/cloud_labshell/stable/runtime.yaml
solutions/cloud_labshell/stable/variables.tf

Add cloud_labshell Terraform Module.

Add: Initial version

---

solutions/cloud_labshell/stable/main.tf
solutions/cloud_labshell/stable/variables.tf

Update to incorporate cloud_labshell.

Add: Refactor service name + properties

---

solutions/cloud_labshell/stable/main.tf
solutions/cloud_labshell/stable/outputs.tf

Incorrect naming of TF property.

Add: Fix Cloud Run rename

---

solutions/cloud_labshell/example/install.sh

Add script directory to Cloud Lab Shell download.

Add: install script

---

basics/lab_project/stable/outputs.tf

Temporary change - remove project ID/NUM from the details.

Add: hide project ID/NUM

---

basics/lab_project/stable/main.tf

Add optional project variable for the module.

Add: optional project

---

basics/lab_project/stable/outputs.tf

Update: data properties

---

solutions/proxy_vertex_workbench/stable/variables.tf

Fix: invalid variable definition

---

basics/gcs_bucket/example/install.sh
basics/gcs_bucket/example/main.tf
basics/gcs_bucket/example/variables.tf

Update the installation notes + example documentation.

Add: install and example doc

---

solutions/proxy_vertex_workbench/stable/main.tf

Amend the allocated location.
Change to use the `allowed_location` property assigned.

Add: update assigned location

---

solutions/proxy_vertex_workbench/stable/main.tf

Invalid configuration.
* Remove Region
* Add Zone
Need to amend the allocated location used by the Vertex Notebook instance.

Add: Amend from region to zone

---

solutions/ide_web/stable/variables.tf

Add default value for username.

Add: default value for Username

---

basics/gke_cluster/example/README.md
basics/gke_cluster/example/install.sh
basics/gke_cluster/example/main.tf
basics/gke_cluster/example/outputs.tf
basics/gke_cluster/example/runtime.yaml
basics/gke_cluster/example/variables.tf
basics/gke_cluster/stable/main.tf
basics/gke_cluster/stable/variables.tf

* Title: GKE Cluster
* Folder: Basic

Add: Version revision

---

README.md
basics/README.md

Update docs to reflect the new IAM module for role binding.

Add: IAM Role binding doc + links

---

cloudbuild.yaml

Add: automated repository sync to bucket

Cloud Build: Rsync to bucket

---

cloudbuild.yaml

Split the processing into sections.
Process should be quicker to complete with the above changes.

Cloud Build: Rsync refactor

---

basics/bq_dataset/README.md
basics/bq_dataset/cloudbuild.yaml
basics/bq_dataset/example/README.md
basics/bq_dataset/example/install.sh
basics/bq_dataset/example/main.tf
basics/bq_dataset/example/outputs.tf
basics/bq_dataset/example/runtime.yaml
basics/bq_dataset/example/variables.tf
basics/bq_dataset/stable/main.tf
basics/bq_dataset/stable/outputs.tf
basics/bq_dataset/stable/provider.tf
basics/bq_dataset/stable/runtime.yaml
basics/bq_dataset/stable/variables.tf

Add: Initial TF Module Version

TF Module: BQ Dataset.

---

basics/bq_dataset/example/main.tf

Amend the data source to use GCS and include examples:

TF Module: BQ Dataset Source

---

basics/bq_dataset/stable/provider.tf
basics/bq_job_load/stable/provider.tf
basics/bq_table/stable/provider.tf

Update:
Reference: [Stackoverflow - depends on](https://stackoverflow.com/questions/67361809/why-am-i-unable-to-add-a-depends-on-block-to-a-module-with-provider-configuratio) discussion.

BQ Module: depends on functionality

---

basics/cloud_run/example/main.tf
basics/cloud_run/example/scripts/lab-init

Module: Cloud Run

---

basics/cloud_run/stable/main.tf

Fix: missing PROJECT_ID from Module.

Cloud Run: Add missing PROJECT value

---

basics/cloud_run/stable/outputs.tf

Add: Format outputs

---

solutions/cloud_code_developer/example/README.md
solutions/cloud_code_developer/example/install.sh
solutions/cloud_code_developer/example/main.tf

Cloud Code Developer: TF Module

---

solutions/cloud_code_developer/example/install.sh

Add: Fix bash script path

---

solutions/cloud_code_developer/example/main.tf
solutions/cloud_code_developer/stable/main.tf

Add: source test github

---

solutions/cloud_code_developer/stable/outputs.tf

Amend output values to use the sub-module.

Add: module output variables

---

solutions/cloud_code_developer/stable/outputs.tf
solutions/lab_proxy/dev/main.tf

Tlf cloud code

---

solutions/lab_proxy/dev/main.tf

Add: dependency on service enable

---

solutions/cloud_code_developer/README.md
solutions/cloud_code_developer/stable/outputs.tf

Enable additional output variables:
> Pass back the VPC + Subnet so module users can add resources to the defined network.

Add: VPC + Subnet access

---

basics/gke_standard/README.md
basics/gke_standard/cloudbuild.yaml
basics/gke_standard/example/README.md
basics/gke_standard/example/install.sh
basics/gke_standard/example/main.tf
basics/gke_standard/example/outputs.tf
basics/gke_standard/example/runtime.yaml
basics/gke_standard/example/variables.tf
basics/gke_standard/stable/main.tf
basics/gke_standard/stable/outputs.tf
basics/gke_standard/stable/provider.tf
basics/gke_standard/stable/runtime.yaml
basics/gke_standard/stable/test.tfvars
basics/gke_standard/stable/variables.tf

Add: New GKE Std module

---

basics/gke_standard/stable/main.tf

Amend basic settings for GKE standard.

Add: gke standard private default

---

basics/gke_standard/stable/main.tf
basics/gke_standard/stable/variables.tf

Temp change - revert back to non private cluster.

Add: test non private cluster

---

basics/gke_standard/stable/main.tf

Remove reference to service account.

Add: remove SA reference

---

solutions/cloud_code_developer/README.md
solutions/cloud_code_developer/example/main.tf
solutions/cloud_code_developer/example/scripts/lab-init
solutions/cloud_code_developer/stable/main.tf
solutions/cloud_code_developer/stable/variables.tf

Update example to include detail on how to incorporate a startup script.

Rosera patch 1

---

basics/app_engine/example/main.tf

Amend source path to correct folder `app_engine`

APP Engine: Source path fix

---

basics/cloud_function/example/install.sh

Fix: Typo for the installation

Add: Installation script fix

---

solutions/dialogflow_webhook/example/README.md

* Update script for downloading Terraform module.
* Update folder used to host Cloud Function

Add: Missing installation script + Cloud Function folder

---

solutions/dialogflow_webhook/example/install.sh

Fix: Folder name typo

---

solutions/dialogflow_webhook/stable/main.tf

Test: Issue with Firestore Document concurrency.

Add: Amend Firestore document concurrency data loading

---

solutions/dialogflow_webhook/stable/main.tf

Update reference to Module as its using an incorrect name.

Fix: Ref Module name for depends statement

---

solutions/dialogflow_webhook/stable/main.tf

Remove embedded Cloud functions 
- Cloud Function require access to source code, so need to be in their own module

Fix: Remove CF to isolated module

---

solutions/dialogflow_webhook/stable/main.tf
solutions/dialogflow_webhook/stable/variables.tf

Test: passing information to Cloud Function.

Add: Cloud Function variables

---

solutions/dialogflow_webhook/stable/variables.tf

Remove the variables used with Cloud Functions.

Fix: redundant variables

---

basics/cloud_function/stable/main.tf

Move the value for the local file as its not picked up

Add: Amend bucket object

---

basics/cloud_function/stable/main.tf

Test:
Move cloud object definition.

Add: Bucket object test

---

basics/cloud_function/stable/main.tf

Fix: 
* Amend - archive_source as value for the source to be loaded.

Fix: Bucket source object

---

basics/cloud_function/stable/main.tf

Fix:
* Move to use `google_storage_bucket_object.archive.source`

Fix: Bucket source object #1

---

basics/cloud_function/stable/main.tf

Remove Cloud Storage and Object from the module.

Remove local Cloud Storage + Object

---

basics/cloud_function/stable/main.tf

Fix: Amend values to use variables to enable multiple concurrent calls to Cloud Function module

Add: Pass properties to resource call

---

README.md
basics/README.md

Documentation: Update for new modules.

---

basics/gce_instance/stable/variables.tf

Amend Map to String object. So it can process more than one object item.

Add: Object for Map

---

basics/gce_instance/stable/variables.tf

Amend MAP to handle general object rather than strings.

Add: Map alternative

---

basics/gce_instance/stable/variables.tf

Add: map(string)

---

basics/gce_instance/stable/main.tf
basics/gce_instance/stable/variables.tf

Add: Amend to default to use Null

---

basics/gce_instance/stable/main.tf

Add: Fix for Zone

---

basics/gce_instance/stable/main.tf

Add null config for startup values.

Add: null option for startup config

---

basics/gce_instance/example/main.tf
basics/gce_instance/stable/main.tf

Add: Migrate metadata config

---

basics/gce_instance/dev/main.tf
basics/gce_instance/dev/outputs.tf
basics/gce_instance/dev/runtime.yaml
basics/gce_instance/dev/test.tfvars
basics/gce_instance/dev/variables.tf

Add development channel for gce_instance updates.

Add: dev channel

---

basics/bq_table/example/README.md
basics/bq_table/stable/main.tf

Add missing project_id property in the BQ Table module

Add: project_id

---

basics/bq_dataset/example/README.md
basics/bq_dataset/example/install.sh
basics/bq_table/example/install.sh
basics/bq_table_view/README.md
basics/bq_table_view/cloudbuild.yaml
basics/bq_table_view/example/README.md
basics/bq_table_view/example/install.sh
basics/bq_table_view/example/main.tf
basics/bq_table_view/example/outputs.tf
basics/bq_table_view/example/runtime.yaml
basics/bq_table_view/example/variables.tf
basics/bq_table_view/stable/main.tf
basics/bq_table_view/stable/outputs.tf
basics/bq_table_view/stable/runtime.yaml
basics/bq_table_view/stable/variables.tf

BQ Table View: New Module

---

basics/bq_table_view/README.md

Add: doc update

---

basics/gke_standard/README.md
basics/gke_standard/preview/main.tf
basics/gke_standard/preview/outputs.tf
basics/gke_standard/preview/provider.tf
basics/gke_standard/preview/runtime.yaml
basics/gke_standard/preview/test.tfvars
basics/gke_standard/preview/variables.tf
basics/gke_standard/stable/main.tf
basics/gke_standard/stable/vpc.tf

* Module: GKE Standard
__NOTE__: 
* Replaces existing GKE Standard module
* Segregating configuration of GKE Standard/Autopilot

GKE Standard: Migrate GKE Standard configuration

---

solutions/fraudfinder/example/install.sh

Add: installation script

---

solutions/fraudfinder/example/install.sh

Add: Amend path to installation script

---

basics/cloud_function_g2/stable/main.tf

Add: storage source - Test Branch!

---

basics/cloud_function_g2/stable/main.tf

Add: Custom Function - Test Branch

---

basics/cloud_function_g2/dev/main.tf

Cloud Functions Gen2: Test Branch

---

basics/gke_standard/stable/main.tf
basics/gke_standard/stable/variables.tf

GKE Standard: Machine Type property

---

basics/gke_standard/stable/main.tf
basics/gke_standard/stable/variables.tf

* Add image custom
* Add node count

GKE Standard: image + node count variable

---

basics/gce_instance/stable/variables.tf

Add: Boot Disk Size as number

---

solutions/fraudfinder/stable/main.tf

- fixed bugs preventing notebooks from running successfully
- added necessary IAM permissions
- removed extraneous service accounts for compute
- removed unnecessary scripts when instantiating JupyterLab instance
Tested on Qwiklabs

Fixes to FraudFinder Terraform

---

basics/gke_standard/stable/main.tf

GKE Standard: Invalid Node Count

---

basics/gke_standard/stable/main.tf

GKE Standard: Redundant code

---

basics/gke_standard/stable/outputs.tf

Remove invalid output variable.

GKE Standard: output value fix

---

basics/gke_standard/stable/main.tf
basics/gke_standard/stable/variables.tf

GKE Standard: Cluster property fix

---

basics/gke_node_pool/stable/main.tf

Set the cluster name to a variable.

GKE Node Pool: Rename resource property

---

basics/gke_standard/stable/main.tf
basics/gke_standard/stable/variables.tf

GKE Standard - Update

---

solutions/generative-ai/README.md
solutions/generative-ai/example/install.sh
solutions/generative-ai/stable/main.tf
solutions/generative-ai/stable/variables.tf

Add: SME config + variable update

SME Generative AI: Review

---

basics/api_service/example/install.sh
basics/app_engine/example/install.sh
basics/bq_dataset/example/install.sh
basics/bq_job_load/example/install.sh
basics/bq_table/example/install.sh
basics/bq_table_view/example/install.sh
basics/cloud_function/example/install.sh
basics/cloud_function_g2/example/install.sh
basics/cloud_run/example/install.sh
basics/cloudsql/example/install.sh
basics/firestore_document/example/install.sh
basics/gce_instance/example/install.sh
basics/gcs_bucket/example/install.sh
basics/gke_cluster/example/install.sh
basics/gke_node_pool/example/install.sh
basics/iam_role_bind/example/install.sh
basics/iam_sa_role/example/install.sh
basics/iam_service_account/example/install.sh
basics/lab_project/example/install.sh
basics/secret_manager/example/install.sh
basics/source_repo/example/install.sh
basics/vai_notebook/example/install.sh
basics/vpc_connector/example/install.sh
basics/vpc_firewall/example/install.sh
basics/vpc_network/example/install.sh

Amend installation script to perform:

Maintenance: Script template unification

---

basics/gce_instance/stable/variables.tf

* Module: gce_instance
* Type: basics
* Channel: stable
Maintenance update to add new defaults:
| Field | Old | New |
|---------|-------|---------|
| OS     | Debian 10 | Debian 11 |
| Machine Type | n1-standard-1 | e2-medium |

Module: gce_instance

---

solutions/asm_cluster/README.md
solutions/asm_cluster/cloudbuild.yaml
solutions/asm_cluster/example/README.md
solutions/asm_cluster/example/install.sh
solutions/asm_cluster/example/main.tf
solutions/asm_cluster/example/variables.tf
solutions/asm_cluster/stable/test copy.tfvars

Module: asm_cluster

---

basics/gke_node_pool/example/main.tf
basics/gke_node_pool/stable/main.tf
basics/gke_node_pool/stable/variables.tf

* Module: GKE Node Pool
* Type: Basic

GKE Node Pool: OAUTH Scope variable

---

solutions/cloudbuild_script/example/outputs.tf

cloudbuild_script: Fix

---

solutions/cloudbuild_script/example/README.md

Updated example information.
* Add script folder information - relates to running a custom script.

cloudbuild_script: Script folder

---

solutions/cloud_code_developer/example/main.tf

Fix: IDE Cloud Code 

---

basics/vai_notebook/README.md
basics/vai_notebook/example/main.tf

Documentation clarification
* How to use the post startup script
* Where to get additional information
* What the post startup script is meant to do

Vertex Notebook: Add Vertex AI startup information

---

solutions/la_generative_ai/example/README.md
solutions/la_generative_ai/example/install.sh

Amend the path for la_generative_ai

la_generative_ai: Amend path to install script

---

solutions/la_generative_ai/README.md
solutions/la_generative_ai/example/main.tf

Add: Update doc + ref

---

basics/vai_notebook/stable/variables.tf

Default the notebook to use the lab-init.sh

Add: Update lab-init.sh

---

basics/cloud_function/example/main.tf
basics/cloud_function/stable/main.tf
basics/cloud_function/stable/variables.tf

Add: Use environment variables option

---

basics/cloud_function/stable/variables.tf

Cloud Functions: variable definition default

---

basics/cloud_function/stable/variables.tf

Unable to reference variable in variable.tf.

Add: variable definition default #2

---

basics/cloud_function/stable/main.tf

Fix environment variables definition

Cloud Functions: environment

---

solutions/random_region/example/outputs.tf

Fix: Example output variables amended to use the module values.

Random Region: Fix Output variables

---

basics/firebase_project/README.md
basics/firebase_project/cloudbuild.yaml
basics/firebase_project/example/README.md
basics/firebase_project/example/install.sh
basics/firebase_project/example/main.tf
basics/firebase_project/example/outputs.tf
basics/firebase_project/example/runtime.yaml
basics/firebase_project/example/scripts/lab-init
basics/firebase_project/example/variables.tf
basics/firebase_project/stable/main.tf
basics/firebase_project/stable/outputs.tf
basics/firebase_project/stable/runtime.yaml
basics/firebase_project/stable/test.tfvars
basics/firebase_project/stable/variables.tf

Add: Firebase Project creation

Firebase Project: Initial Version

---

activity-tracking/bq_dataset_create/stable/main.tf
activity-tracking/fw_rule_create/stable/main.tf
activity-tracking/gcs_bucket_create/stable/main.tf
activity-tracking/log_sink_create/stable/main.tf
activity-tracking/pubsub_sub_create/stable/main.tf
activity-tracking/pubsub_topic_create/stable/main.tf
activity-tracking/source_repo_create/stable/main.tf
activity-tracking/vpc_network_create/stable/main.tf
activity-tracking/vpc_subnet_create/stable/main.tf

Activity Tracking - Include the done status

---

activity-tracking/gcs_bucket_object/README.md
activity-tracking/gcs_bucket_object/stable/main.tf
activity-tracking/gcs_bucket_object/stable/variable.tf

Module: gcs_bucket_oject
Activity Tracking: Template
Validate the existence of a text object in a Storage Bucket.

Storage Bucket Object

---

activity-tracking/gcs_bucket_object/stable/variable.tf

GCS Bucket Object
* Add: AT default name change

GCS Object

---

basics/gke_autopilot/README.md
basics/gke_autopilot/cloudbuild.yaml
basics/gke_autopilot/example/README.md
basics/gke_autopilot/example/install.sh
basics/gke_autopilot/example/main.tf
basics/gke_autopilot/example/outputs.tf
basics/gke_autopilot/example/runtime.yaml
basics/gke_autopilot/example/variables.tf
basics/gke_autopilot/stable/main.tf
basics/gke_autopilot/stable/outputs.tf
basics/gke_autopilot/stable/provider.tf
basics/gke_autopilot/stable/runtime.yaml
basics/gke_autopilot/stable/test.tfvars
basics/gke_autopilot/stable/variables.tf

Module: GKE Autopilot
Type: Basics
A general GKE Autopilot cluster is provisioned.

GKE Autopilot: Initial Version

---

basics/vpc_network/example/main.tf
basics/vpc_network/example/outputs.tf

VPC_Network

---

solutions/ide_cloud_code/stable/main.tf

Fix: Firewall sub module definition.

Add: Fix Child module Firewall rule

---

activity-tracking/README.md
activity-tracking/bq_dataset_create/stable/main.tf
activity-tracking/bq_table_create/README.md
activity-tracking/bq_table_create/stable/main.tf
activity-tracking/bq_table_create/stable/variable.tf
activity-tracking/fw_rule_create/README.md
activity-tracking/gcs_bucket_create/README.md
activity-tracking/gcs_bucket_object/README.md
activity-tracking/log_sink_create/README.md
activity-tracking/log_sink_create/stable/main.tf
activity-tracking/pass_step_check/README.md
activity-tracking/pubsub_sub_create/README.md
activity-tracking/pubsub_topic_create/README.md
activity-tracking/source_repo_create/README.md
activity-tracking/source_repo_create/stable/main.tf
activity-tracking/vpc_network_create/README.md
activity-tracking/vpc_subnet_create/README.md

Title: Generic Activity Tracking
Updated list of modules and user documentation.

TLF Activity Tracking.

---

activity-tracking/bq_dataset_create/README.md
activity-tracking/bq_table_create/README.md
activity-tracking/fw_ingress_create/README.md
activity-tracking/fw_rule_create/README.md
activity-tracking/fw_tag_create/README.md
activity-tracking/gcs_bucket_create/README.md
activity-tracking/gcs_bucket_object/README.md
activity-tracking/log_sink_create/README.md
activity-tracking/pubsub_sub_create/README.md
activity-tracking/pubsub_topic_create/README.md
activity-tracking/source_repo_create/README.md
activity-tracking/vpc_network_create/README.md
activity-tracking/vpc_subnet_create/README.md

Add a link to the Google Ruby googleapis documentation.

Add: Googleapis reference link

---

basics/cloud_function/dev/main.tf
basics/cloud_function/dev/variables.tf

Cloud Function Update:
Channel: Dev

CF Gen1 properties - AR Migration

---

basics/cloud_function/dev/main.tf

Cloud Function Update
Channel: Dev

CF Gen 1 Fix: HTTP Trigger Security Level property

---

basics/cloud_function/example/main.tf
basics/cloud_function/example/outputs.tf
basics/cloud_function/stable/main.tf
basics/cloud_function/stable/variables.tf

Cloud Function Update
Channel: Dev

Cloud Function Gen 1: Promote Dev Channel to Stable

---

activity-tracking/log_object_filter/README.md
activity-tracking/log_object_filter/stable/main.tf
activity-tracking/log_object_filter/stable/variable.tf

Log Object Filter: Initial version

---

activity-tracking/README.md
activity-tracking/bq_dataset_create/README.md
activity-tracking/bq_table_create/README.md
activity-tracking/fw_ingress_create/README.md
activity-tracking/fw_rule_create/README.md
activity-tracking/fw_tag_create/README.md
activity-tracking/gcs_bucket_create/README.md
activity-tracking/gcs_bucket_object/README.md
activity-tracking/log_object_filter/README.md
activity-tracking/log_sink_create/README.md
activity-tracking/pass_step_check/README.md
activity-tracking/pubsub_sub_create/README.md
activity-tracking/pubsub_topic_create/README.md
activity-tracking/source_repo_create/README.md
activity-tracking/vpc_network_create/README.md
activity-tracking/vpc_subnet_create/README.md

Apply language formatting for better readability of examples.

Add: Ruby Language formatting.

---

basics/vai_workbench/stable/variables.tf
basics/vai_workbench/stable/workbench.tf

Add: Custom network capability

---

basics/vai_workbench/stable/variables.tf
basics/vai_workbench/stable/workbench.tf

Amend default settings for networking:

Add: Network defaults for NIC + STACK

---

basics/vpc_network/stable/main.tf

Address VPC delay in creation to ensure subnet has more time for creation.

Add: VPC delay before subnet creation

---

basics/vpc_network/stable/main.tf

Depends On needs to be on the object rather than the object properties.

Fix: Set depends on object

---

activity-tracking/bq_job_create/README.md
activity-tracking/bq_job_create/stable/main.tf
activity-tracking/bq_job_create/stable/variable.tf

Add a new activity tracking template for BQ Job.

Add: BQ Job AT

---

activity-tracking/README.md
activity-tracking/bq_job_create/README.md

Add a new activity tracking template for BQ Job.

Add: Documentation

---

solutions/proxy_vertex_workbench/stable/v1/api.tf
solutions/proxy_vertex_workbench/stable/v1/cr.tf
solutions/proxy_vertex_workbench/stable/v1/fw.tf
solutions/proxy_vertex_workbench/stable/v1/outputs.tf
solutions/proxy_vertex_workbench/stable/v1/sa.tf
solutions/proxy_vertex_workbench/stable/v1/variables.tf
solutions/proxy_vertex_workbench/stable/v1/vpc.tf
solutions/proxy_vertex_workbench/stable/v1/workbench.tf

Draft version of Vertex Workbench
Vertex Workbench and Proxy.
Uses the new modules for:

Add: Vertex Workbench V1

---

basics/vai_workbench/stable/v1/variables.tf

Remove default network reference. Default network setting will be set to an empty object.

Add: Optional default network null

---

basics/vai_workbench/example/main.tf

Vertex Workbench

---

basics/vai_notebook/README.md
basics/vai_notebook/dev/api.tf
basics/vai_notebook/dev/iam.tf
basics/vai_notebook/dev/notebook.tf
basics/vai_notebook/dev/outputs.tf
basics/vai_notebook/dev/provider.tf
basics/vai_notebook/dev/sa.tf
basics/vai_notebook/dev/variables.tf
basics/vai_notebook/example/main.tf

Vertex AI: Notebook Basic Module

Tlf notebook

---

basics/vai_notebook/stable/v1/api.tf
basics/vai_notebook/stable/v1/iam.tf
basics/vai_notebook/stable/v1/notebook.tf
basics/vai_notebook/stable/v1/outputs.tf
basics/vai_notebook/stable/v1/provider.tf
basics/vai_notebook/stable/v1/runtime.yaml
basics/vai_notebook/stable/v1/sa.tf
basics/vai_notebook/stable/v1/variables.tf

Vertex Notebook 
Promote to V1
> Note: [Use Workbench module](https://github.com/CloudVLab/terraform-lab-foundation/tree/main/basics/vai_workbench)

Add: Vertex Notebook Modular

---

solutions/proxy_vertex_workbench/stable/v1/variables.tf

Vertex Workbench
Proxy Terraform code

Add: Proxy lab init script

---

solutions/proxy_vertex_workbench/stable/v1/workbench.tf

Vertex AI Workbench Proxy Service.

Add: Post Startup Script

---

solutions/proxy_vertex_workbench/example/main.tf

Vertex Workbench
Update Proxy to use Google Cloud Storage.

Add: V1 Path + GCS source

---

solutions/ide_cloud_code/stable/v1/api.tf
solutions/ide_cloud_code/stable/v1/cr.tf
solutions/ide_cloud_code/stable/v1/fw.tf
solutions/ide_cloud_code/stable/v1/gce.tf
solutions/ide_cloud_code/stable/v1/outputs.tf
solutions/ide_cloud_code/stable/v1/provider.tf
solutions/ide_cloud_code/stable/v1/runtime.yaml
solutions/ide_cloud_code/stable/v1/variables.tf
solutions/ide_cloud_code/stable/v1/versions.tf
solutions/ide_cloud_code/stable/v1/vpc.tf

IDE Cloud Code Module
Add v1 Proxy Module promotion from  dev channel.
__NOTE:__ Stable channel remains the default, until soak test completes.

Add: IDE V1 Proxy

---

basics/identity_service/dev/README.md
basics/identity_service/dev/outputs.tf
basics/identity_service/dev/prj_service_id.tf
basics/identity_service/dev/runtime.yaml
basics/identity_service/dev/variables.tf
basics/identity_service/example/README.md
basics/identity_service/example/install.sh
basics/identity_service/example/main.tf
basics/identity_service/example/outputs.tf
basics/identity_service/example/runtime.yaml
basics/identity_service/example/variable.tf

Request: New module relating to Vertex AI workbook issue.

Add: Dev Channel Identity Service

---

basics/identity_service/README.md
basics/identity_service/example/MODULE.md
basics/identity_service/example/README.md

Add top level `README.md` and amend the example docs to show both module properties + installation examples.

Add: More docs

---

basics/iam_role_bind/dev/MODULE.md
basics/iam_role_bind/dev/provider.tf

Remove: Provider from module. Move provider definition to the parent.

IAM_ROLE_BIND: Remove Provider

---

basics/iam_role_bind/dev/main.tf
basics/iam_role_bind/dev/variables.tf

IAM_ROLE_BIND: Amend dev channel variable name

---

basics/iam_role_bind/stable/provider.tf
basics/iam_sa_role/stable/provider.tf
basics/iam_service_account/stable/provider.tf

Updates to existing `basics` modules to remove `provider.tf` files:

removed provider from child modules to prevent module loading issues

---

basics/iam_role_bind/stable/provider.tf
basics/iam_sa_role/stable/provider.tf
basics/iam_service_account/stable/provider.tf

Reverts CloudVLab/terraform-lab-foundation#419
Lab change breaks TLF.

Revert "removed provider from child modules to prevent module loading issues"

---

solutions/proxy_automl/example/main.tf
solutions/proxy_automl/example/variables.tf

Amend AutoML Gateway example:
Add clarification to AutoML Gateway example for variables required.

Add: Gateway variable for examples

---

solutions/proxy_automl/example/variables.tf

AutoML Proxy: variable update

---

activity-tracking/bq_dataset_create/stable/bigquery_dataset_check.rb
activity-tracking/bq_table_create/stable/bigquery_table_check.rb

First step to enhance Activity Tracking MVP.

Add: Activity Tracking

---

basics/cloud_function_g2/dev/main.tf
basics/cloud_function_g2/dev/variables.tf

Cloud Run function: Gen 2

---

solutions/asm_cluster/stable/main.tf
solutions/bigquery_soccer/stable/provider.tf
solutions/cloud_code_developer/stable/provider.tf
solutions/cloud_labshell/stable/main.tf
solutions/cloud_labshell/stable/provider.tf
solutions/cloudbuild_script/example/provider.tf
solutions/fraudfinder/stable/provider.tf
solutions/generative-ai/stable/provider.tf
solutions/ide_cloud_code/dev/provider.tf
solutions/ide_cloud_code/dev/versions.tf
solutions/ide_cloud_code/example/provider.tf
solutions/ide_cloud_code/stable/provider.tf
solutions/ide_cloud_code/stable/v1/provider.tf
solutions/ide_cloud_code/stable/v1/versions.tf
solutions/ide_cloudshell/dev/main.tf
solutions/ide_cloudshell/dev/provider.tf
solutions/ide_cloudshell/stable/provider.tf
solutions/ide_tensorflow/stable/main.tf
solutions/ide_tensorflow/stable/provider.tf
solutions/ide_web/stable/provider.tf
solutions/la_generative_ai/stable/provider.tf
solutions/lab_proxy/dev/main.tf
solutions/proxy_automl/dev/provider.tf
solutions/proxy_automl/stable/provider.tf
solutions/proxy_vertex_workbench/dev/main.tf
solutions/proxy_vertex_workbench/stable/main.tf

Ref:  https://buganizer.corp.google.com/issues/397636095

Add: google-beta fix

---

basics/api_service/README.md
basics/api_service/cloudbuild.yaml
basics/api_service/dev/README.md
basics/api_service/dev/test.tfvars
basics/api_service/stable/README.md
basics/api_service/stable/test.tfvars
basics/api_service/stable/v1/README.md
basics/api_service/stable/v1/test.tfvars
basics/api_service/stable/variables.tf

Add documentation for modules:

TEST: API Service

---

basics/cloud_function_g2/dev/README.md
basics/cloud_function_g2/dev/main.tf
basics/cloud_function_g2/dev/variables.tf
basics/cloud_function_g2/stable/v1/README.md
basics/cloud_function_g2/stable/v1/main.tf
basics/cloud_function_g2/stable/v1/variables.tf

Add Custom Service Account option.

Add: Custom Gen 2 Service Account option

---

basics/cloud_function_g2/dev/main.tf
basics/cloud_function_g2/stable/v1/main.tf

Fix: Ensure Environment variables are available to build + service

Cloud Function Gen 2: ENV VAR

---

solutions/set_persona/README.md
solutions/set_persona/cloudbuild.yaml
solutions/set_persona/example/TERRAFORM.md
solutions/set_persona/example/install.sh
solutions/set_persona/example/persona.tf
solutions/set_persona/example/variables.tf
solutions/set_persona/stable/README.md

Refresh Personal Module.
Use this module in the new A100 labs to define a persona for each scenario.

Add: Persona module refresh

---

solutions/set_persona/example/variables.tf

Append descriptions for default variables.

Add: Fix for Variable descriptions

---

basics/vpc_subnet/dev/v1/outputs.tf
basics/vpc_subnet/dev/v1/subnet.tf

Migrate code to separate VPC and Subnet functionality.

Add: Cleanup network separation

---

basics/vpc_subnet/dev/v1/subnet.tf
basics/vpc_subnet/dev/v1/variables.tf

Set network to variable - meaning network needs to be passed to the subnet module.

Add: Network information for subnet

---

basics/vpc_network/dev/v1/outputs.tf

Add network id as output variable to push to subnetwork.

Add: Network identifier

---

solutions/gen_ai_models/dev/main.tf
solutions/gen_ai_models/dev/outputs.tf

- Add support for `gemini-2.5-flash-image` model to Dev channel
- Add support for `multimodalembedding@001` model to Dev channel

Add Gemini 2.5 Flash Lite/Image + Multimodal Embeddings Models
