CloudVLab/terraform-lab-foundation

README.md
Migrate to Terraform Modules
Fix broken links to top level markdown.
=> Fix: Bad link ref

basics/vai_notebook/README.md, basics/vai_notebook/stable/main.tf, basics/vai_notebook/stable/variables.tf
Update the example to include Vertex Notebook startup script.
=> Add: Vertex AI startup bash script

basics/vpc_firewall/stable/main.tf, basics/vpc_firewall/stable/variables.tf
Add processing similar to [Cloud Foundation Toolkit](https://github.com/terraform-google-modules) Firewall module:
=> Add: Firewall rules module - handle objects

solutions/ide_web/stable/main.tf
Amend GCE Instance to use the [Basics Module](https://github.com/CloudVLab/terraform-lab-foundation/tree/solution-ide/basics/gce_instance)
=> Add: Migrate module to use GCE module

solutions/ide_web/stable/main.tf
=> Add: fix for invalid fw rule + invalid network

basics/gce_instance/stable/main.tf, basics/vpc_connector/example/README.md, basics/vpc_connector/example/main.tf, basics/vpc_connector/example/outputs.tf, basics/vpc_connector/example/runtime.yaml, basics/vpc_connector/example/scripts/lab-init, basics/vpc_connector/example/variables.tf, basics/vpc_firewall/example/README.md, basics/vpc_firewall/example/main.tf, basics/vpc_firewall/example/outputs.tf, basics/vpc_firewall/example/runtime.yaml, basics/vpc_firewall/example/scripts/lab-init, basics/vpc_firewall/example/variables.tf, basics/vpc_network/example/README.md, basics/vpc_network/example/main.tf, basics/vpc_network/example/outputs.tf, basics/vpc_network/example/runtime.yaml, basics/vpc_network/example/variables.tf
Fix general network assignment.
```
network_interface {
network = var.gce_machine_network == "default" ? var.gce_machine_network : null
subnetwork = var.gce_machine_network == "default" ? null : var.gce_machine_network
access_config {
// Ephemeral IP
}
}
```
The above enables the GCE module to use the correct configuration based on the assumption that the `default` network is the one provided by Google Cloud.
If the network/subnet name is changed, the assumption is the network is a custom network!
=> Tlf maintenance

solutions/appsheet_cloudsql/README.md, solutions/appsheet_cloudsql/example/main.tf, solutions/appsheet_cloudsql/example/scripts/lab-init
Updated AppSheet + Cloud SQL configuration
=> Add: example VM database configuration

solutions/ide_gke_developer/dev/main.tf
Amend GKE Autopilot set to false. Using NULL to indicate the property should use the default state.
Ref: [Terraform Types](https://www.terraform.io/language/expressions/types#types)
=> Add: null value for gke autopilot false state

basics/gke_cluster/dev/main.tf, basics/gke_cluster/dev/variables.tf
Replace the use of a custom network with new defaults
=> Add: gke network/subnet default selection

basics/gke_cluster/dev/main.tf, basics/gke_cluster/dev/variables.tf
Amend values to use empty set.
Terraform uses null to represent an empty set. Switch the module for GKE to use null rather than false, to avoid conflict in properties.
=> Add: null property to indicate empty set

basics/gke_cluster/dev/main.tf
Replace typo in variable name.
=> Fix: variable typo

basics/gke_cluster/dev/main.tf
Redefine the `ip_allocation_policy`
=> Add: redefine ip_allocation_policy

basics/gce_instance/README.md, basics/gce_instance/example/main.tf, basics/gce_instance/stable/main.tf, basics/gce_instance/stable/variables.tf
Add GCE custom service account
=> Gce instance

solutions/ide_web/stable/outputs.tf
Expose the network as an output variable. Enable module users to add resources to the custom network used.
```
output "vpcNetworkName" {
value       = "${module.la_vpc.vpc_network_name}"
description = "Name of the GCE instance"
}
```
=> Add: VPC network as output variable

solutions/ide_cloud_code/dev/main.tf, solutions/ide_cloud_code/dev/variables.tf
Reference: [container_cluster](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster)
location - (Optional) The location (region or zone) in which the cluster master will be created, as well as the default node location. If you specify a zone (such as us-central1-a), the cluster will be a zonal cluster with a single cluster master. If you specify a region (such as us-west1), the cluster will be a regional cluster with multiple masters spread across zones in the region, and with default node locations in those zones as well
=> Add: location variable

solutions/ide_cloud_code/dev/main.tf
=> Add: switch to GKE autopilot

solutions/proxy_vertex_workbench/dev/main.tf
Amend to use `random_string` to avoid regex error on generation of id.
=> Fix: amend to random_string to avoid invalid characters

solutions/proxy_vertex_workbench/stable/main.tf
Module: Proxy Vertex Workbench
Repo: terraform-lab-foundation/solutions
Sometimes the "google_vpc_access_connector" would fail with the following error: "Connector ID must follow the pattern ^[a-z][-a-z0-9]{0,23}[a-z0-9]"
The randomly generated string resource would sometimes begin with a number and break the specified pattern.
This change ensures the name begins with a letter, something coherent, and has a randomly generated suffix as well.
=> Fix: workbench proxy vpc connector name gen

basics/gcs_bucket/README.md, basics/gcs_bucket/example/main.tf, basics/gcs_bucket/stable/main.tf, basics/gcs_bucket/stable/variables.tf
Module: GCS_STORAGE
Folder: Basics
Feedback from content authors to enable project name to be used. Current best practice is to combine the project_id with a bucket name to enable a unique reference. Updated the module so authors can override this with a name of their choosing.
=> Google Cloud Storage - Amend naming policy

basics/cloud_run/example/main.tf
Updated example showing how to override the default __environment variables__
=> Cloud Run: document environment variable support

basics/gke_standard/README.md, basics/gke_standard/example/main.tf, basics/gke_standard/stable/main.tf, basics/gke_standard/stable/variables.tf
Migrate module to allow choice of cluster
Ref: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#location
* A zonal cluster will have a single controller applied
* A regional cluster will have multiple controllers applied
=> Add: choice of cluster Zonal/Regional

solutions/cloud_code_developer/stable/main.tf, solutions/cloud_code_developer/stable/variables.tf
Add the ability to pass startup to cloud code.
=> Add: Startup script handler

basics/firestore_document/example/main.tf
Amend the example variable definition:
* Pass an object to Firestore Document using JSON. 
* Ensure the field is correctly formatted as shown below:
```
gfd_document_data = {"field_1"= {"stringValue"="Test"}}
```
=> Fix: variable definition

basics/cloud_function/example/install.sh
Rename Cloud Functions to Cloud Function in the installation script.
=> Fix: Typo Cloud Functions

basics/cloud_function/stable/main.tf
Replace source value with object name.
=> Add: Replace bucket object name

basics/gce_instance/stable/main.tf, basics/gce_instance/stable/variables.tf
Module: gce_instance
Enable Metadata configuration within the GCE Instance.
=> Add: Custom Metadata as a Map

basics/gce_instance/stable/main.tf
Add sensible default for gce_zone.
=> Add: Zone default

basics/gce_instance/stable/main.tf, basics/gce_instance/stable/variables.tf
Add sensible defaults as folks are now starting to use startup scripts + metadata for compute resources.
default(s)
=> Add: Override processing + Default values

basics/vai_notebook/stable/outputs.tf
Accessing the name is helpful for integrating this module with other resources if needed and doesn't affect the existing code.
=> add notebook_name as output for vai_notebook_basic module

basics/vai_notebook/stable/outputs.tf
Accidentally left this defined as a variable. Fixing the defintion.
=> fix: incorrect output definition

basics/gke_standard/stable/variables.tf
=> GKE Standard: Fix redundant variable

solutions/ide_cloud_code/dev/main.tf, solutions/ide_cloud_code/stable/main.tf, solutions/ide_cloudshell/stable/main.tf, solutions/ide_tensorflow/stable/main.tf, solutions/ide_web/dev/main.tf, solutions/ide_web/stable/main.tf, solutions/lab_proxy/dev/main.tf, solutions/proxy_vertex_workbench/dev/main.tf, solutions/proxy_vertex_workbench/stable/main.tf
HotFix
Reset region setting. Ensure Cloud Run + VPC Connector are placed in the same region.
Region setting derived from the platform. Set both resources to the same setting to avoid issues.
=> Hotfix: Tlf ide vpc connector

solutions/fraudfinder/example/README.md, solutions/fraudfinder/example/install.sh
=> OSL001: FraudFinder installation doc + script

basics/gce_instance/stable/main.tf
Add: boot name consistency.
Change the boot disk to the same name as the instance.
=> GCE Instance: boot disk name value

basics/gke_standard/stable/main.tf
Amend module to place image type within the cluster auto-scale block.
=> GKE Standard: Move block to cluster auto-scale

basics/gce_instance/stable/variables.tf
* Module: GCE Instance
* Buganizer: https://buganizer.corp.google.com/issues/274896557
=> Add: Google Cloud platform default changed to 100GB

solutions/ide_web/example/main.tf, solutions/ide_web/stable/main.tf, solutions/ide_web/stable/variables.tf
=> IDE Web: IDE_Web/GCE Instance Disk Size property

basics/iam_service_account/README.md, basics/iam_service_account/cloudbuild.yaml, basics/iam_service_account/example/README.md, basics/iam_service_account/example/install.sh, basics/iam_service_account/example/main.tf, basics/iam_service_account/example/outputs.tf, basics/iam_service_account/example/runtime.yaml, basics/iam_service_account/example/variables.tf, basics/iam_service_account/stable/main.tf, basics/iam_service_account/stable/outputs.tf, basics/iam_service_account/stable/provider.tf, basics/iam_service_account/stable/runtime.yaml, basics/iam_service_account/stable/variables.tf
* Module: iam_service_account
Separate the creation of an IAM account into an isolated module.  Use this module in conjunction with role bind to create an account member with associated permissions.
=> Module iam_service_account: Initial version

solutions/cloudbuild_script/README.md, solutions/cloudbuild_script/cloudbuild.yaml, solutions/cloudbuild_script/example/README.md, solutions/cloudbuild_script/example/install.sh, solutions/cloudbuild_script/example/main.tf, solutions/cloudbuild_script/example/outputs.tf, solutions/cloudbuild_script/example/provider.tf, solutions/cloudbuild_script/example/runtime.yaml, solutions/cloudbuild_script/example/scripts/lab-init.sh, solutions/cloudbuild_script/example/variables.tf
Cloud Build script invoker.
Provides the ability to use Cloud Build rather than use a Compute instance. To use follow the guidance in the Google Doc.
=> cloudbuild_script: Initial version

solutions/lab_proxy/dev/main.tf, solutions/lab_proxy/dev/outputs.tf, solutions/lab_proxy/dev/variables.tf
[VPC connectors](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vpc_access_connector) must not specify on of the following:
* max_throughput
* max_instances
Updated the Terraform module to include the `min_throughput` and `max_throughput` settings.
=> LA Proxy - add mandatory parameters

solutions/generative-ai/stable/main.tf, solutions/generative-ai/stable/variables.tf
Notebook instance was previously using an older TF image, which was causing conflicts with the latest google-cloud-aiplatform Python SDK. This PR fixes the problem.
=> fix: update notebook instance

solutions/ide_cloud_code/stable/main.tf, solutions/ide_cloud_code/stable/outputs.tf, solutions/ide_cloud_code/stable/variables.tf
TLF Migration:
General housekeeping activity to update to use modules with modules. Migrate from `VPC Connectors` to `VPC Direct` for Cloud Run to VPC connectivity.
=> Add: VPC Direct support

solutions/ide_cloud_code/stable/main.tf, solutions/ide_cloud_code/stable/variables.tf
=> Add: Firewall + Variables to enable comms

solutions/ide_cloud_code/stable/main.tf
=> Add: VPC Fw rule to allow default to talk to custom

basics/vai_notebook/stable/variables.tf
Module:  VIA_NOTEBOOK
Ref: https://buganizer.corp.google.com/issues/326388441
=> Debian 11 Upgrade

solutions/proxy_vertex_workbench/stable/variables.tf
Migrate lab from Debian 10 to Debian 11.
Ref: https://buganizer.corp.google.com/issues/326388441
=> Verrext AI Workbook: Transition to Debian 11

basics/cloud_function/dev/variables.tf
Cloud Function Update
Channel: Dev
Ref: https://developer.hashicorp.com/terraform/language/expressions/types
=> CF Gen 1 Fix: Data type invalid

basics/cloud_function/dev/variables.tf
Cloud Function Update
Channel: Dev
Amend docker registry to have a default of Container Registry. A temporary step to ease the transition to Artifact Registry.
Dev Channel can be promoted to stable, with this change.
=> CF Gen 1: Amend the docker registry

basics/cloud_function/example/main.tf, basics/cloud_function/example/outputs.tf, basics/cloud_function/stable/main.tf, basics/cloud_function/stable/variables.tf
Reverts CloudVLab/terraform-lab-foundation#373
We're seeing a bunch of lab launch errors across Qwiklabs after this PR got merged. Reverting for now because we think that will fix the problem.
I know the formatting is terrible but hopefully this error is almost human-readable:
```
INFO 2024-04-05T14:22:55.415505433Z [resource.labels.instanceId: 7725423000572245687] Execution failed, message for user: [Error executing terraform apply [Error: Unsupported argument], see logs for additional details.]\r\n
INFO 2024-04-05T14:22:55.415600045Z [resource.labels.instanceId: 7725423000572245687] Command returned status 1. Logs: [\x1b[31m\xe2\x95\xb7\x1b[0m\x1b[0m\r\n
INFO 2024-04-05T14:22:55.415631361Z [resource.labels.instanceId: 7725423000572245687] \x1b[31m\xe2\x94\x82\x1b[0m …
```
=> Revert "Cloud Function Gen 1: Promote Dev Channel to Stable"

basics/gce_instance/dev/outputs.tf
=> GCE: Output variable custom for bool value

basics/gce_instance/dev/outputs.tf
=> GCE: Fix for invalid variable name

basics/cloud_run/example/main.tf, basics/cloud_run/example/versions.tf, basics/cloud_run/stable/v1/main.tf, basics/cloud_run/stable/v1/outputs.tf, basics/cloud_run/stable/v1/runtime.yaml, basics/cloud_run/stable/v1/test.tfvars, basics/cloud_run/stable/v1/variables.tf, basics/cloud_run/stable/v2/api.tf, basics/cloud_run/stable/v2/cr.tf, basics/cloud_run/stable/v2/fw.tf, basics/cloud_run/stable/v2/gce.tf, basics/cloud_run/stable/v2/outputs.tf, basics/cloud_run/stable/v2/provider.tf, basics/cloud_run/stable/v2/runtime.yaml, basics/cloud_run/stable/v2/variables.tf, basics/cloud_run/stable/v2/vpc.tf
Cloud Run
Start the migration away from Cloud Run v1 to Cloud Run v2.
-  [ ] Added Stable V1 and V2 folder to split out existing functionality
-  [ ] Stable V1 - Cloud Run Gen 1
-  [ ] Stable V2 - Cloud Run Gen 2
=> Add: Initial migration effort split out of Cloud Run

basics/iam_role_bind/stable/main.tf, basics/iam_role_bind/stable/variables.tf
Fix: missing SA display name
```terraform
variable "iam_sa_display" {
type        = string
description = "Display name for the SA"
default     = "tester-qwiklabs account" 
}
variable "iam_sa" {
type        = string
description = "Display name for the SA"
default     = "tester-qwiklabs account" 
}
```
=> Tlf workbench

basics/vai_workbench/stable/workbench.tf
Stack type not available - still in beta.
Removing from module.
=> Fix: stack_type not in GA

solutions/ide_tensorflow/stable/main.tf
Tensorflow VPC connector.
* Note this module is no longer used - any lab using this module, should be migrated to an alternative i.e. Workbench.
=> Add: Tensorflow fix for VPC Connector

solutions/generative-ai/stable/main.tf
Modify the terraform script to create a Workbench Instance, instead of a User-Managed Instance.
Reference:
- [Latest tf docs on deploying Vertex AI Workbench Instances](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/workbench_instance)
- `post-startup-script` is used within the `metadata` field: [documentation](https://cloud.google.com/vertex-ai/docs/workbench/instances/manage-metadata#keys)
=> use Workbench Instances instead of User-Managed Instances for the generative-ai solution

basics/gce_instance/stable/variables.tf
Module: GCE Instance
Channel: Stable
Per conversation with QL Eng. It looks like the stable channel logic has a bug.
Amend the `stable` channel variable to use the same default as the `V1 method. Code expects a null is as default to allow the user to default to the `var.gcp_region` or `var.gcp_zone`.
=> hotfix: gce instance variable default should be null

solutions/proxy_vertex_workbench/example/main.tf, solutions/proxy_vertex_workbench/stable/v1/api.tf, solutions/proxy_vertex_workbench/stable/v1/cr.tf, solutions/proxy_vertex_workbench/stable/v1/fw.tf, solutions/proxy_vertex_workbench/stable/v1/sa.tf, solutions/proxy_vertex_workbench/stable/v1/variables.tf, solutions/proxy_vertex_workbench/stable/v1/vpc.tf, solutions/proxy_vertex_workbench/stable/v1/workbench.tf
=> Proxy Workbench: Migration to Cloud Storage + Variable to disable external IP

basics/cloud_run/example/versions.tf, basics/cloud_run/stable/v2/provider.tf, basics/firebase_project/stable/main.tf, basics/gke_autopilot/stable/gke_autopilot.tf, basics/gke_autopilot/stable/provider.tf, basics/gke_cluster/dev/main.tf, basics/gke_cluster/dev/provider.tf, basics/gke_cluster/stable/main.tf, basics/gke_cluster/stable/provider.tf, basics/gke_node_pool/stable/provider.tf, basics/gke_standard/preview/main.tf, basics/gke_standard/preview/provider.tf, basics/gke_standard/stable/main.tf, basics/gke_standard/stable/provider.tf, basics/vai_workbench/example/versions.tf, basics/vpc_connector/stable/main.tf
Reverts CloudVLab/terraform-lab-foundation#434
I am not sure if this PR is quite right - the `google beta` provider is actually needed in many cases.
Also, as per https://github.com/hashicorp/terraform-provider-google/issues/21493, I think the underlying issue is fixed.
=> Revert "Add: google-beta fix - Basics"
